### ISSUE TITLE
Trouble booting after installing upstart/sysv

### ISSUE THREAD

**Issue by ar-jan** [gdm85/ubuntu16-no-systemd#1]
This project looks very useful! My question is actually more about the [instructions you wrote](http://without-systemd.org/wiki/index.php/How_to_remove_systemd_from_an_Ubuntu_Xenial_installation) for removing systemd than this repo itself, but I'm hoping you have some ideas.

I've followed the removal instructions on a fresh install of Ubuntu 16.04.3, with xfce4 added. After doing

    apt-get install upstart-sysv sysvinit-utils
    update-initramfs -u

and then rebooting, the Ubuntu boot screen simply turns blank after I've succesfully unlocked sda5_crypt. I have no idea what could be wrong. Do you have any suggestions?

**Comment by gdm85** [comment]
Sorry, this is not on topic here. I suggest you open a question at StackOverflow.

cryptsetup is one of the least maintained/tested features of Debian/Ubuntu, no surprise that you got that problem.

In your case it might not be cryptsetup at all but I would rather look into the login manager logs for some problem. By inspecting the logs you should be able to find the problem.
